// <auto-generated />
using System;
using CompassSurvey.Data;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

namespace CompassSurvey.Migrations
{
    [DbContext(typeof(CompassDbContext))]
    [Migration("20201217113331_changes")]
    partial class changes
    {
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .UseIdentityColumns()
                .HasAnnotation("Relational:MaxIdentifierLength", 128)
                .HasAnnotation("ProductVersion", "5.0.1");

            modelBuilder.Entity("CompassSurvey.Models.Option", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .UseIdentityColumn();

                    b.Property<int?>("QuestionId")
                        .HasColumnType("int");

                    b.Property<int?>("SurveyAnswerId")
                        .HasColumnType("int");

                    b.Property<string>("Text")
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.HasIndex("QuestionId");

                    b.HasIndex("SurveyAnswerId");

                    b.ToTable("Option");
                });

            modelBuilder.Entity("CompassSurvey.Models.Question", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .UseIdentityColumn();

                    b.Property<string>("CreatedBy")
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTime?>("CreatedDateTime")
                        .HasColumnType("datetime2");

                    b.Property<int>("QuestionType")
                        .HasColumnType("int");

                    b.Property<string>("SubTitle")
                        .HasColumnType("nvarchar(max)");

                    b.Property<int?>("SurveyQuestionId")
                        .HasColumnType("int");

                    b.Property<string>("Title")
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.HasIndex("SurveyQuestionId");

                    b.ToTable("Question");
                });

            modelBuilder.Entity("CompassSurvey.Models.SurveyAnswer", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .UseIdentityColumn();

                    b.Property<int>("QuestionId")
                        .HasColumnType("int");

                    b.Property<int?>("SelectedOptionId")
                        .HasColumnType("int");

                    b.Property<string>("SubmittedBy")
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("SurveyId")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.HasIndex("SelectedOptionId");

                    b.ToTable("SurveyAnswer");
                });

            modelBuilder.Entity("CompassSurvey.Models.SurveyQuestion", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .UseIdentityColumn();

                    b.Property<string>("name")
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.ToTable("SurveyQuestion");
                });

            modelBuilder.Entity("CompassSurvey.Models.Option", b =>
                {
                    b.HasOne("CompassSurvey.Models.Question", null)
                        .WithMany("Options")
                        .HasForeignKey("QuestionId");

                    b.HasOne("CompassSurvey.Models.SurveyAnswer", null)
                        .WithMany("Options")
                        .HasForeignKey("SurveyAnswerId");
                });

            modelBuilder.Entity("CompassSurvey.Models.Question", b =>
                {
                    b.HasOne("CompassSurvey.Models.SurveyQuestion", null)
                        .WithMany("Questions")
                        .HasForeignKey("SurveyQuestionId");
                });

            modelBuilder.Entity("CompassSurvey.Models.SurveyAnswer", b =>
                {
                    b.HasOne("CompassSurvey.Models.Option", "SelectedOption")
                        .WithMany()
                        .HasForeignKey("SelectedOptionId");

                    b.Navigation("SelectedOption");
                });

            modelBuilder.Entity("CompassSurvey.Models.Question", b =>
                {
                    b.Navigation("Options");
                });

            modelBuilder.Entity("CompassSurvey.Models.SurveyAnswer", b =>
                {
                    b.Navigation("Options");
                });

            modelBuilder.Entity("CompassSurvey.Models.SurveyQuestion", b =>
                {
                    b.Navigation("Questions");
                });
#pragma warning restore 612, 618
        }
    }
}
